# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '60_debate_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 60_debate_iOS
 
  #pod 'Alamofire', '~> 5.5'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'KeychainAccess'

end
