# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '60_debate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 60_debate
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
end
